### PR TITLE
Update service-gateway-service-account.md

### PR DESCRIPTION
**Pull request by aarontguilmette**
Added instructions for updating the DG to a gMSA account.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@aarontguilmette - can you agree to the CLA? Instructions here: https://github.com/MicrosoftDocs/data-integration/pull/344#issuecomment-1961684143

**Comment by aarontguilmette** [comment]
@microsoft-github-policy-service agree

**Comment by jonburchel** [comment]
This has been merged. Thanks for helping us improve the docs, @aarontguilmette! #please-close

**Comment by aarontguilmette** [comment]
hey, just following up here. I noticed that it got pushed (woo!) but the contributors wasn't updated. Is that no longer done, or just takes a bit longer? Thanks!

**Comment by jonburchel** [comment]
Oh my apologies @aarontguilmette! Normally if I tag the public PR in my private PR, it will automatically get merged, and the public PR's author may be added to contributors then. For some reason this time even though I tagged the public PR, it didn't get closed automatically, so I had to manually close it, and unfortunately, this seems to have avoided adding you to the contributor list. If you want to submit a new public PR with any very minor change, I can try again and merge it after tagging yours to see if your name will get added then. Hopefully it will work!

Jon

**Comment by aarontguilmette** [comment]
> Oh my apologies @aarontguilmette! Normally if I tag the public PR in my private PR, it will automatically get merged, and the public PR's author may be added to contributors then. For some reason this time even though I tagged the public PR, it didn't get closed automatically, so I had to manually close it, and unfortunately, this seems to have avoided adding you to the contributor list. If you want to submit a new public PR with any very minor change, I can try again and merge it after tagging yours to see if your name will get added then. Hopefully it will work!
> 
> Jon

No worries! I made a teensy change so hopefully the process works as intended. :-)

**Pull request closed without merging**
